const fs = require("fs");
const path = require("path");
const hre = require("hardhat");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  const network = await hre.ethers.provider.getNetwork();

  console.log("Deploying CarPassport with:", deployer.address);
  console.log("Network chainId:", network.chainId.toString());

  const Factory = await hre.ethers.getContractFactory("CarPassport");
  const passport = await Factory.deploy();
  await passport.waitForDeployment();
  const address = await passport.getAddress();

  console.log("CarPassport deployed to:", address);

  const artifact = await hre.artifacts.readArtifact("CarPassport");
  const frontendDir = path.join(__dirname, "..", "frontend");
  fs.mkdirSync(frontendDir, { recursive: true });
  const outPath = path.join(frontendDir, "deployed-address.js");
  const contents = `// Auto-generated by scripts/deploy.js — do not edit by hand
window.CARPASSPORT_DEPLOYED_ADDRESS = "${address}";
window.CARPASSPORT_DEPLOYED_CHAIN_ID = ${network.chainId.toString()};
`;
  fs.writeFileSync(outPath, contents);
  console.log("Wrote", outPath);

  const abiPath = path.join(frontendDir, "abi.js");
  fs.writeFileSync(
    abiPath,
    `// Auto-generated ABI from Hardhat artifacts
window.CARPASSPORT_ABI = ${JSON.stringify(artifact.abi, null, 2)};
`
  );
  console.log("Wrote", abiPath);

  if (network.chainId === 80002n) {
    const explorer = `https://amoy.polygonscan.com/address/${address}`;
    console.log("PolygonScan:", explorer);

    const amoyJs = path.join(frontendDir, "amoy-deployment.js");
    fs.writeFileSync(
      amoyJs,
      `// Auto-generated by scripts/deploy.js on Polygon Amoy
window.CARPASSPORT_AMOY_ADDRESS = "${address}";
window.CARPASSPORT_AMOY_EXPLORER = "https://amoy.polygonscan.com";
`
    );
    console.log("Wrote", amoyJs);

    fs.writeFileSync(
      path.join(frontendDir, "amoy-deployment.json"),
      JSON.stringify(
        {
          address,
          chainId: 80002,
          explorer,
          network: "polygon-amoy",
        },
        null,
        2
      ) + "\n"
    );
    console.log("Wrote", path.join(frontendDir, "amoy-deployment.json"));
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
